Feature/treemap: TreeMap visualization
mrunal-z/observability pull request #1
Opened 2022-04-22 10:57 UTC by mrunal-z

Signed-off-by: Mrunal Zambre <mrunal_zambre@persistent.com>

### Description
1. Added treemap visualization upto 2 levels
2. Added snapshot test case for treemap

### Issues Resolved
[List any issues this PR will resolve]

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass, including unit test, integration test and doctest
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
  - [ ] New functionality has user manual doc added
- [ ] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2022-04-25 13:22 UTC, abasatwar approved these changes
added only 1 suggestion. Please update and commit.

2022-04-25 13:22 UTC, abasatwar commented on dashboards-observability/public/components/visualizations/charts/maps/treemap_type.ts
> +                mapTo: 'labelField',
can we make this child filed.

2022-04-26 06:49 UTC, spattnaik requested changes

2022-04-26 06:49 UTC, spattnaik commented on dashboards-observability/public/components/visualizations/charts/maps/treemaps.tsx
> +    ...(layoutConfig.layout && layoutConfig.layout),
The spread operator can create a problem. The code in brackets is going to produce a boolean (false) if `layoutConfig.layout` is empty or null. Again, there should be a key in the object that can take this boolean as a value. For `||`, we are sure that the statement always returns the last value if everything fails.

2022-04-26 10:36 UTC, abasatwar approved these changes

2022-04-28 14:13 UTC, closed without merging